version: "3"
services:
  authentication:
    container_name: authentication
    build:
      context: backend/authentication
      dockerfile: dockerfile
    volumes:
      - ./backend/authentication:/app
    env_file: .env
    ports:
      - 5000:5000
    depends_on:
      - redis
      - rabbitmq

  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/usr/local/etc/redis/
      - ./redis.conf:/usr/local/etc/redis.conf
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD:-admin1234}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_DATABASES=${REDIS_DATABASES:-16}
    command: redis-server /usr/local/etc/redis.conf

  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq/data/:/var/lib/rabbitmq/
      - ./rabbitmq/log/:/var/log/rabbitmq

  meilisearch:
    image: getmeili/meilisearch:latest
    container_name: "meilisearch"
    restart: always
    volumes:
      - ./meilisearch/data.ms:/data.ms
    ports:
      - "7700:7700"
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_MASTER_KEY:-ms}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7700"]
      interval: 10s
      timeout: 5s
      retries: 5

  meilisearch-admin:
    image: riccoxie/meilisearch-ui:latest
    container_name: "meilisearch-admin"
    restart: always
    ports:
      - "24900:24900"
    depends_on:
      - meilisearch

  meilisync:
    platform: linux/amd64
    container_name: "meilisync"
    image: long2ice/meilisync
    restart: always
    volumes:
      - ./meilisync.yml:/meilisync/config.yml
      - ./meilisync/progress.json:/meilisync/progress.json
    depends_on:
      - meilisearch
